### ISSUE TITLE
Error on loading extension

### ISSUE THREAD

**Issue by AugustePop** [jasonsanjose/brackets-sass#132]
My Platform: Arch Linux x64
Brackets: Release 1.3 experimental build 1.3.0-16022 (release cd0a6aae5) 
Extension: 2.0.1-109

Here's the error message:
> [node-error 11:14:07 AM] [Launcher] uncaught exception at top level, exiting. TypeError: Cannot call method 'charAt' of undefined
    at Object.exports.normalize (path.js:336:27)
    at /home/pop/.config/Brackets/extensions/user/jasonsanjose.brackets-sass/node/2.0.1/SASSDomain.js:405:35
    at Array.forEach (native)
    at /home/pop/.config/Brackets/extensions/user/jasonsanjose.brackets-sass/node/2.0.1/SASSDomain.js:404:29
    at renderMsg._callback (/home/pop/.config/Brackets/extensions/user/jasonsanjose.brackets-sass/node/2.0.1/SASSDomain.js:319:18)
    at ChildProcess._nextRender.messageListener (/home/pop/.config/Brackets/extensions/user/jasonsanjose.brackets-sass/node/2.0.1/SASSDomain.js:194:13)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:345:11) 

I tried the recompile thing on issue #106's [comment](https://github.com/jasonsanjose/brackets-sass/issues/106#issuecomment-100088939) and get the same error.

After the error,
> [node-info 11:14:07 AM] [Server] stopping
> File watchers went offline!

**Comment by jasonsanjose** [comment]
@AugustePop can you try the latest update 2.0.3?

**Comment by AugustePop** [comment]
Still the same. Brackets SASS version: 2.0.3-132

```
[node-error 11:38:07 AM] [Launcher] uncaught exception at top level, exiting. TypeError: Cannot call method 'charAt' of undefined
    at Object.exports.normalize (path.js:336:27)
    at /home/pop/.config/Brackets/extensions/user/jasonsanjose.brackets-sass/node/2.0.3/SASSDomain.js:404:35
    at Array.forEach (native)
    at /home/pop/.config/Brackets/extensions/user/jasonsanjose.brackets-sass/node/2.0.3/SASSDomain.js:403:29
    at renderMsg._callback (/home/pop/.config/Brackets/extensions/user/jasonsanjose.brackets-sass/node/2.0.3/SASSDomain.js:318:18)
    at ChildProcess._nextRender.messageListener (/home/pop/.config/Brackets/extensions/user/jasonsanjose.brackets-sass/node/2.0.3/SASSDomain.js:193:13)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:345:11) 
```

I removed all other plugins, before testing this. This problem does not show up on my Mac, so I guess it's somewhat related to my Linux environment.

**Comment by marmistrz** [comment]
Arch Linux user, same problem here.

**Comment by gverm** [comment]
@AugustePop @marmistrz Sorry for the late response, is this still an issue? I'll be testing Linux compatibility tomorrow. I know it is broken, but I will do my best to try and fix it ASAP and roll out another update.
