### ISSUE TITLE
New version 2.0.2-128 not working in windows

### ISSUE THREAD

**Issue by zavvla** [jasonsanjose/brackets-sass#137]
Don't compil.
Error with nodejs and error message "clearup"

1 SCSS Problem
×
Error: `libsass` bindings not found in C:\Users\zavadv\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.2\node_modules\node-sass\vendor\win32-ia32-11\binding.node. Try reinstalling `node-sass`? at Object.sass.getBinaryPath (C:\Users\zavadv\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.2\node_modules\node-sass\lib\extensions.js:148:11) at Object.<anonymous> (C:\Users\zavadv\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.2\node_modules\node-sass\lib\index.js:16:36) at Module._compile (module.js:456:26) at Object.Module._extensions..js (module.js:474:10) at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12) at Module.require (module.js:364:17) at require (module.js:380:17) at Object.<anonymous> (C:\Users\zavadv\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.2\render.js:39:12) at Module._compile (module.js:456:26)	
Version brackets: Release 1.3 build 1.3.0-16022

**Comment by zavvla** [comment]
I downloaded and filled in the missing library in the specified path, and all start.
Library downloaded here: https://github.com/sass/node-sass/releases/
