### ISSUE TITLE
dlopen, cleanup error

### ISSUE THREAD

**Issue by prejr-dev** [jasonsanjose/brackets-sass#166]
I am running a freshly installed brackets on mac, with only extract and the sass extension. The sass extension wont transpile the scss file. It reports a 'cleanup' issue and sometimes a dlopen issue. I can't trouble shoot it beyond this.

**Comment by prejr-dev** [comment]
Found an error message. I am not sure how to investigate this further
```
[node-error 12:11:34 PM] [Launcher] uncaught exception at top level, exiting. TypeError: Cannot call method 'charAt' of undefined
    at Object.exports.normalize (path.js:336:27)
    at /Users/*/Library/Application Support/Brackets/extensions/user/jasonsanjose.brackets-sass/node/2.0.3/SASSDomain.js:404:35
    at Array.forEach (native)
    at /Users/*/Library/Application Support/Brackets/extensions/user/jasonsanjose.brackets-sass/node/2.0.3/SASSDomain.js:403:29
    at renderMsg._callback (/Users/*/Library/Application Support/Brackets/extensions/user/jasonsanjose.brackets-sass/node/2.0.3/SASSDomain.js:318:18)
    at ChildProcess._nextRender.messageListener (/Users/*/Library/Application Support/Brackets/extensions/user/jasonsanjose.brackets-sass/node/2.0.3/SASSDomain.js:193:13)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:345:11)
```

**Comment by marmistrz** [comment]
I have the same problem. Don't have the error message from post 2. At first I have a 'cleanup' error, after saving: 'max connections attempt reached'

**Comment by trahibidadido** [comment]
Same thing on Linux

**Comment by EliteSpartan** [comment]
Same thing on Windows 10 x64

**Comment by gverm** [comment]
@prejr-dev @marmistrz @trahibidadido @EliteSpartan Try this release: https://github.com/Brainzyy/brackets-sass/releases/tag/2.0.4
EDIT: An official update has been rolled out through Brackets.
