### ISSUE TITLE
Cleanup error when i update brackets v 1.9

### ISSUE THREAD

**Issue by jedeveraa** [jasonsanjose/brackets-sass#190]
Hi Brainzyy thank you for supporting this plugin!

When i update brackets v 1.9 the cleanup error always shows up and not compiling.

**Comment by bobbybol** [comment]
Same here.. same problem as when the 1.8 version came out

**Comment by gverm** [comment]
@jedeveraa @bobbybol I'll see what I can do tonight.

**Comment by jedeveraa** [comment]
thanks @gverm

**Comment by ghost** [comment]
`Error: `libsass` bindings not found in C:\Users\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\vendor\win32-ia32-48\binding.node. Try reinstalling `node-sass`? at Object.sass.getBinaryPath (C:\Users\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\lib\extensions.js:148:11) at Object.<anonymous> (C:\Users\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\lib\index.js:16:36) at Module._compile (module.js:541:32) at Object.Module._extensions..js (module.js:550:10) at Module.load (module.js:458:32) at tryModuleLoad (module.js:417:12) at Function.Module._load (module.js:409:3) at Module.require (module.js:468:17) at require (internal/module.js:20:19) at Object.<anonymous> (C:\Users\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\render.js:39:12)`

Since upgraded to 1.9.

**Comment by gverm** [comment]
@jedeveraa @bobbybol @gfaiers Could you try this version: 
[test version download](https://mega.nz/#!dwNRmKAR!emTP8ZQXq5nfe4ZobHkjsZco_3BpzcC6BUktMGodP-Q)
Be sure to remove your old version first and just reinstall by dragging this zip to the extension manager.

EDIT: I tested this test version on Win 7 (64bit) and it worked on 1.9, please let me know how it works for you and which OS you used.

**Comment by bobbybol** [comment]
Test version works ;) (on Win10-x64)
Not tested for performance or anything, just checked if it compiled and it did so fine.
What exactly fixed the issue? Perhaps we can figure out a more robust solution so the plugin doesn't break on every Brackets update..
Thanks @gverm and cheers!

**Comment by gverm** [comment]
@bobbybol This plugin relies on node-sass. For some reason every new Brackets release adds some new checks or features that require a new version of the pre-packaged node-sass. I don't think there's a better way to fix this without rewriting the whole plugin.

**Comment by nickpish** [comment]
@gverm I was just about to post re Brackets 1.9 when I saw this thread-- I can confirm your fix is working on Win10x64 as well. Thank you for the fix!!

**Comment by wkaskie** [comment]
I am experiencing this same issue on Mac OS X v10.11.6.  The test version will not load "due to unknown internal error"

**Comment by doige** [comment]
[test version download](https://mega.nz/#!dwNRmKAR!emTP8ZQXq5nfe4ZobHkjsZco_3BpzcC6BUktMGodP-Q) from @gverm 
works fine with brackets 1.9 and win10.

Any experiences with Brackets 1.10?

**Comment by gverm** [comment]
@wkaskie @doige Try this version, please uninstall first. https://mega.nz/#!N0lDmB5Z!N32mfb_YTtt6facHH0vkoCPHWq9tWD--jHiKAUPyqQ8

**Comment by photografx** [comment]
Hello! its 2018 and the Problem is still here !?
Brackets 1.11
Brackets SASS 2.0.5
on Win7-64
@gverm your version inst available anymore :(

**Comment by RodionPro** [comment]
Привет из 2018 года.
Использую Windows 10 64x и Brackets 1.12
Но ошибка Cleanup до сих пор не исправлена((((

**Comment by RodionPro** [comment]
@gverm 
this link does not work

https://mega.nz/#!N0lDmB5Z!N32mfb_YTtt6facHH0vkoCPHWq9tWD--jHiKAUPyqQ8

**Comment by AmerDajeh** [comment]
@gverm 
can you re upload the files :)
