### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by AmitMDesign** [jasonsanjose/brackets-sass#197]
Error: `libsass` bindings not found in C:\Users\amitmdesign\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\vendor\win32-ia32-48\binding.node. Try reinstalling `node-sass`? at Object.sass.getBinaryPath (C:\Users\amitmdesign\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\lib\extensions.js:148:11) at Object.<anonymous> (C:\Users\amitmdesign\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\node_modules\node-sass\lib\index.js:16:36) at Module._compile (module.js:541:32) at Object.Module._extensions..js (module.js:550:10) at Module.load (module.js:458:32) at tryModuleLoad (module.js:417:12) at Function.Module._load (module.js:409:3) at Module.require (module.js:468:17) at require (internal/module.js:20:19) at Object.<anonymous> (C:\Users\amitmdesign\AppData\Roaming\Brackets\extensions\user\jasonsanjose.brackets-sass\node\2.0.3\render.js:39:12)
--

help me plz

**Comment by lucasmontec** [comment]
I'm having the same problem.

**Comment by gverm** [comment]
@AmitMDesign @lucasmontec try this version: https://mega.nz/#!N0lDmB5Z!N32mfb_YTtt6facHH0vkoCPHWq9tWD--jHiKAUPyqQ8

**Comment by robertjallen** [comment]
same here

**Comment by gverm** [comment]
@bobbidigi Can you try the version linked above?

**Comment by robertjallen** [comment]
I just downloaded but not sure how to install
Never used a zip for extensions. Whats the next step

**Comment by gverm** [comment]
@bobbidigi Open the extension tab and drag the zip into it, but make sure all older version of the plugin were removed first.

**Comment by Rafiozoo** [comment]
Alternative source for working [Brackets SASS @ v. 2.0.7](https://www.dropbox.com/s/luv13lpaf2mi6rc/jasonsanjose.brackets-sass.zip?dl=0) 
// I'm on Brackets 1.10

**Comment by robertjallen** [comment]
k thanks check back in a min if you have time.

**Comment by robertjallen** [comment]
its not letting me drag the file into the zip area. It might be because I have wnirar.

**Comment by ahuseyn** [comment]
@Rafiozoo thank you so much! I've wasted 2 days on it and after giving up found your link. version 2.0.7 is only working solution for me. (on Brackets 1.13) And I'm very angry about this plugin with poor documentation and full of errors! Unfortunately there is no alternative for this plugin.

**Comment by RodionFadeev** [comment]
@Rafiozoo ОГРОМНОЕ ТЕБЕ СПАСИБО! Я на Brackets 1.13 и плагин по твоей ссылке работает с этой версией. Ещё раз тебе большое спасибо!!!

@Rafiozoo THANK YOU VERY MUCH! I'm on brackets 1.13 and the plugin on your link works with this version. Once again many thanks to you !!!
